spring:
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: ${GLOBAL_KAFKA_HOST_PLAIN:localhost:9092}
    consumer:
      group-id: ${MS_NAME:customer_service}
      bootstrap-servers: ${GLOBAL_KAFKA_HOST_PLAIN:localhost:9092}
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/customers}
    username: ${SPRING_DATASOURCE_USERNAME:customer}
    password: ${SPRING_DATASOURCE_PASSWORD:bxshaq06gi4hgdss}
    hikari:
      maximum-pool-size: 100
      minimum-idle: 5
      idle-timeout: 20000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        jdbc:
          time_zone: ${TIME_ZONE:UTC}
        format_sql: true

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVLET_CONTEXT_PATH:}
  error:
    include-stacktrace: always
    include-message: always
