app:
  description: account service is a Spring Boot applications
  name: account_service
  environment: ${ENVIRONMENT:dev}
  ms:
    customer-service:
      url: ${CUSTOMER_SERVICE_URL:http://localhost:8080}
spring:
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: ${GLOBAL_KAFKA_HOST_PLAIN:localhost:9092}
    consumer:
      group-id: ${MS_NAME:account_service}
      bootstrap-servers: ${GLOBAL_KAFKA_HOST_PLAIN:localhost:9092}
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/accounts}
    username: ${SPRING_DATASOURCE_USERNAME:account}
    password: ${SPRING_DATASOURCE_PASSWORD:bxshaq06gi4hgdss}
    hikari:
      maximum-pool-size: 100
      minimum-idle: 5
      idle-timeout: 20000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        jdbc:
          time_zone: ${TIME_ZONE:UTC}
        format_sql: true

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVLET_CONTEXT_PATH:}
  error:
    include-stacktrace: always
    include-message: always
resilience4j:
  retry:
    instances:
      customerClientRetry:
        maxAttempts: 5
        waitDuration: 5000ms
        retryExceptions:
          - java.io.IOException
        ignoreExceptions:
          - java.net.SocketTimeoutException

  circuitbreaker:
    instances:
      customerClientCircuit:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10000ms
        failureRateThreshold: 50
        eventConsumerBufferSize: 10