version: '3.8'

services:
  account_service:
    image: account_service:latest  # Usa una imagen construida previamente y subida a un registro
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_account:5432/accounts
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      CUSTOMER_SERVICE_URL: http://customer-service:8080
      MS_NAME: account_service
    depends_on:
      - db_account

  db_account:
    image: postgres:15  # Imagen de base de datos
    environment:
      POSTGRES_DB: accounts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

