version: '3.8'

services:
  app:
    build: .
    container_name: account_service
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_account:5432/account
      SPRING_DATASOURCE_USERNAME: account
      SPRING_DATASOURCE_PASSWORD: bxshaq06gi4hgdss
    depends_on:
      - db_account
    restart: unless-stopped

  db_account:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: account
      POSTGRES_USER: account
      POSTGRES_PASSWORD: bxshaq06gi4hgdss
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
