version: '3.8'

services:
  customer_service:
    image: customer_service:latest  # Usa la imagen construida previamente y subida a un registro
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_customer:5432/customers
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      MS_NAME: customer_service

  db_customer:
    image: postgres:15  # Imagen de base de datos
    environment:
      POSTGRES_DB: customers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

