version: '3.8'

services:
  app:
    build: .
    container_name: customer_service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_customer:5432/customer
      SPRING_DATASOURCE_USERNAME: customer
      SPRING_DATASOURCE_PASSWORD: bxshaq06gi4hgdss
    depends_on:
      - db_customer
    restart: unless-stopped

  db_customer:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: customer
      POSTGRES_USER: customer
      POSTGRES_PASSWORD: bxshaq06gi4hgdss
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
